apiVersion: v1
kind: Secret
metadata:
  name: fastpay-secrets
  namespace: fastpay
type: Opaque
stringData:
  JWT_ACCESS_SECRET: change-me-access-local-k8s
  JWT_REFRESH_SECRET: change-me-refresh-local-k8s
  MONGO_INITDB_ROOT_USERNAME: fastpay_root
  MONGO_INITDB_ROOT_PASSWORD: change-me-root-dev
  MONGO_APP_USER: fastpay_app
  MONGO_APP_PASSWORD: change-me-app-dev
  MONGO_BACKUP_USER: fastpay_backup
  MONGO_BACKUP_PASSWORD: change-me-backup-dev
  MONGO_RO_USER: fastpay_ro
  MONGO_RO_PASSWORD: change-me-ro-dev
  MONGO_EXPRESS_USER: admin
  MONGO_EXPRESS_PASSWORD: change-me-express-dev
  MONGODB_URI: mongodb://fastpay_app:change-me-app-dev@mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/FastPay?authSource=FastPay&replicaSet=rs0
