apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastpay

resources:
  - namespace.yaml
  - configmap.yaml
  - data/mongo-configmap.yaml
  - data/mongo-init-configmap.yaml
  - data/mongodb-statefulset.yaml
  - data/mongo-init-rs-job.yaml
  - data/mongo-backup-cronjob.yaml
  - data/redis-deployment.yaml
  - data/rabbitmq-statefulset.yaml
  - data/mock-horizon-deployment.yaml
  - apps/api-gateway-deployment.yaml
  - apps/auth-service-deployment.yaml
  - apps/payment-service-deployment.yaml
  - apps/blockchain-service-deployment.yaml
  - apps/fraud-service-deployment.yaml
  - apps/kyc-service-deployment.yaml
  - apps/audit-service-deployment.yaml
  - apps/stubs-deployment.yaml
  - networking/ingress.yaml
  - networking/network-policies.yaml

patches:
  - path: patches/pod-security.yaml
