apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
  namespace: fastpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-service
  template:
    metadata:
      labels:
        app: fraud-service
        fastpay.io/mongo-client: "true"
    spec:
      initContainers:
        - name: wait-mongo
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z mongo 27017; do echo waiting for mongo; sleep 2; done
      containers:
        - name: fraud-service
          image: fastpay-backend:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE
              value: fraud-service
          envFrom:
            - configMapRef:
                name: fastpay-config
            - secretRef:
                name: fastpay-secrets
          ports:
            - containerPort: 3011
          volumeMounts:
            - name: mongo-tls
              mountPath: /etc/mongo-tls
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: 3011
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3011
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: mongo-tls
          secret:
            secretName: mongo-tls
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  namespace: fastpay
spec:
  selector:
    app: fraud-service
  ports:
    - port: 3011
      targetPort: 3011
