import type { AssistantIntent } from "../types";

export const INTENT_EXEMPLARS: Record<AssistantIntent, string[]> = {
  navigate: [
    "go to wallet",
    "open bills",
    "take me to analytics",
    "navigate to settings",
    "show me buy screen",
    "where is kyc",
    "how do i open transfer",
    "find loan page",
  ],
  balance: [
    "how much do i have",
    "what is my balance",
    "wallet balance",
    "show my usdt",
    "how much btc do i hold",
    "solana portfolio",
    "public key address",
    "crypto holdings",
  ],
  cash_flow: [
    "cash flow this month",
    "where did my money go",
    "am i overspending",
    "can i afford 50000",
    "spending vs income",
    "burn rate",
    "expenses breakdown",
    "income and spend",
  ],
  planning: [
    "help me save more",
    "financial plan",
    "how should i manage money",
    "savings plan advice",
    "guide me on budgeting",
    "money management tips",
    "plan my finances",
    "what should i do next financially",
  ],
  budget: [
    "budget status",
    "savings goal progress",
    "spend percent",
    "family plan budget",
    "analytics goals",
    "how much have i saved toward",
    "budget split",
  ],
  kyc: [
    "kyc status",
    "verify my identity",
    "national id upload",
    "proof of address",
    "complete verification",
    "increase kyc level",
  ],
  passcode: [
    "reset passcode",
    "forgot transaction pin",
    "change passcode",
    "pin reset",
    "forgot my pin",
  ],
  product_help: [
    "how do i send money",
    "pay a bill",
    "apply for a loan",
    "buy airtime with momo",
    "use escrow",
    "offline payment",
    "insurance plans",
    "convert crypto",
  ],
  external_info: [
    "usd exchange rate",
    "forex eur",
    "rra tax info",
    "irembo services",
    "stellar horizon status",
    "government fees",
  ],
  general: ["hello", "what can you do", "help", "thanks", "who are you"],
};
